### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [Jefferson-K/prj-rev-bwfs-dasmoto#3]
Overall met expectations.

So in this first project I look for a couple things here.  My goal is to stop what I consider to be bad practices early.

In the html I look to see if you use divs, classes/ids to manage and organize your html.

Excellent on this.

In the css I look to see if you had any repetition or unneeded styling.  

Excellent on this also.

I do look for a couple other items such css/html formatting and you were great on this too.

To prepare you for upcoming projects, go to flexboxfroggy.com, see how far you can get. The later projects use flexbox heavily.

**Comment by Jefferson-K** [comment]
Thank you for your review and feedback, Farish.
